name: NodeJS with Grunt

on:
  push:
    branches: [ "maingit-branch--m-main-<BRANCH>-git-fetch-origin-git-branch--u-origin/<BRANCH>-<BRANCH>-git-remote-set-head-origin--a" ]
  pull_request:
    branches: [ "pinyo98logistics-co<BRANCH>winport98/<BRANCH>-<BRANCH>-git-remote-set-head-origin--a" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        grunt
